version: '2'

services:
  bot:
   build: .
   ports:
   - '127.0.0.1:32779:3000'
   environment:
   - CLIENT_ID
   - CLIENT_SECRET
   - CLIENT_SIGNING_SECRET
   - VERIFICATION_TOKEN
   - REDIRECT_URI
   - DB_NAME=/code/data/bot.sqlite
   volumes:
   - ./data:/code/data/
